config/routes.rb
Quiz::Application.routes.draw do
  devise_for :users
  get "welcome/index"

  resources :problems
  resources :exams do
    member do
      get 'take' # need a special route to take an exam
      post 'result' # and other special route to see the results of a taken exam
    end
  end

  root 'welcome#index'

end

app/models/exam.rb
class Exam < ActiveRecord::Base
  has_and_belongs_to_many :problems

  validates :title, presence: true

  accepts_nested_attributes_for :problems

  class Result
    def initialize(problem, user_answer)
      @problem = problem
      @given_answer = user_answer
    end

    def worth
      @problem.worth
    end

    def score
      @problem.score(user_answer)
    end

    def question
      @problem.question
    end

    def correct_answer
      @problem.answer
    end

    def user_answer
      @given_answer
    end
  end

  class Reporter
    def initialize(exam, user_answers)
      @exam = exam
      @results = []

      @exam.problems.each {
        |current_problem|
        puts user_answers
        @results << Result.new(current_problem, user_answers[current_problem.id.to_s])
      }
    end

    def score
      @results.inject(0) {
        |score_so_far, current_result|
        score_so_far + current_result.score
      }
    end

    def total_possible
      @results.inject(0) {
        |total_so_far, current_result|
        total_so_far + current_result.worth
      }
    end

    def results
      @results
    end
  end

  def evaluate(user_answers)
    Reporter.new(self, user_answers)
  end

  def possible_operators
    ["+", "-", "*"]
  end

  def generate_problems(number_of_problems, number_of_operands, operand_min, operand_max, given_operators)
    rng = Random.new
    number_of_problems.times {
      expression = rng.rand(operand_min..operand_max).to_s
      (number_of_operands-1).times {
        current_operand = rng.rand(operand_min..operand_max).to_s
        current_operator = given_operators.sample
        expression += " " + current_operator + " " + current_operand
      }

      evaluated = eval expression
      self.problems << Problem.new({question: expression, answer: evaluated})
    }
  end
end

app/models/problem.rb
class Problem < ActiveRecord::Base
  has_and_belongs_to_many :exams
  
  validates :question, presence: true
  validates :answer, presence: true

  def score(user_answer)
    user_answer == answer ? 1 : 0
  end

  def worth
    return 1
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # validates :is_teacher, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def authorize_teacher!
    if user_signed_in? && current_user.is_teacher
      return
    elsif user_signed_in?
      flash[:notice] = 'You must be an authorized Teacher to do that!'
      redirect_to :root
    else
      flash[:notice] = 'You need to sign in first!'
      redirect_to new_user_session_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :is_teacher
    devise_parameter_sanitizer.for(:account_update) << :is_teacher
  end
=begin
  def devise_parameter_sanitizer
    if resource_class == User
      User::ParameterSanitizer.new(User, :user, params)
    else
      super
    end
  end
=end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_filter :authorize_teacher!, :except => [:index, :show, :take, :result]
  def new
    @exam = Exam.new
  end

  def create
    @exam = Exam.new(params[:exam].permit(:title, problem_ids: []))

    if @exam.save
      @exam.generate_problems(params[:exam][:number_of_problems].to_i, params[:exam][:number_of_operands].to_i, params[:exam][:operand_min].to_i, params[:exam][:operand_max].to_i, params[:exam][:chosen_operators])
      @exam.save
      redirect_to @exam
    else
      render 'new'
    end
  end

  def show
    @exam = current_exam(params)
  end

  def index
    @exams = Exam.all
  end

  def edit
    @exam = current_exam(params)
  end

  def update
    @exam = current_exam(params)

    if @exam.update_attributes(params[:exam].permit(:title, problem_ids: []))
      @exam.generate_problems(params[:exam][:number_of_problems].to_i, params[:exam][:number_of_operands].to_i, params[:exam][:operand_min].to_i, params[:exam][:operand_max].to_i, params[:exam][:chosen_operators])
      @exam.save
      redirect_to @exam
    else
      render 'edit'
    end
  end

  def destroy
    @exam = current_exam(params)
    @exam.destroy

    redirect_to exams_path
  end

  # As a Student, take an existing exam
  def take
    @exam = current_exam(params)
  end

  # As a Student, see what score you got on the exam you just took
  def result
    @exam = current_exam(params)

    @exam_reporter = @exam.evaluate(params[:answers])
  end

  private
  def current_exam(parameters)
    return Exam.find(parameters[:id])
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_filter :authorize_teacher!
  def new
    @problem = Problem.new
  end

  def create
    @problem = Problem.new(params[:problem].permit(:question, :answer))
    
    if @problem.save
      redirect_to @problem
    else
      render 'new'
    end
  end

  def show
    @problem = Problem.find(params[:id])
  end

  def index
    @problems = Problem.all
  end

  def edit
    @problem = Problem.find(params[:id])
  end

  def update
    @problem = Problem.find(params[:id])

    if @problem.update(params[:problem].permit(:question, :answer))
      redirect_to @problem
    else
      render 'edit'
    end
  end

  def destroy
    @problem = Problem.find(params[:id])
    @problem.destroy

    redirect_to problems_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/views/common/_session.html.erb
<%- if user_signed_in? %>
  <%= link_to current_user.email, edit_user_registration_path %> | <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
<%- else %>
  <%= link_to 'Register', new_user_registration_path %> | <%= link_to 'Sign In', new_user_session_path %>
<%- end %>

app/views/exams/_form.html.erb
<%= form_for @exam do |f| %>
  <% if @exam.errors.any? %>
    <div class="error_explanation">
      <h3><%= pluralize(@exam.errors.count, "error") %> prevented this Quiz from being saved:</h3>
      <ul>
        <% @exam.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h3><%= f.label :title %></h3>
  <%= f.text_field :title %>

  <h2>Create Randomized problems for this Quiz:</h2>
  <strong>How many problems would you like to generate?</strong>
  <%= text_field_tag 'exam[number_of_problems]' %><br />
  <strong>How many Operands should each problem have?</strong>
  <%= text_field_tag 'exam[number_of_operands]' %><br />
  <strong>What Range should each Operand fall in?</strong>
  <%= text_field_tag 'exam[operand_min]' %> to <%= text_field_tag 'exam[operand_max]' %>

  <h3>Which Operators do you want included?</h3>
  <% @exam.possible_operators.each do |operator| %>
    <%= check_box_tag "exam[chosen_operators][]", operator %>
    <%= operator %><br />
  <% end %>

  <h2>Choose from Available Problems:</h2>
  <table>
    <tr>
      <th>Include</th>
      <th>Question</th>
      <th>Answer</th>
      <th></th>
    </tr>

    <% Problem.all.each do |prob| %>
      <%= f.fields_for "exam[problem_ids][]", prob do |builder| %>
        <tr>
          <td><%= check_box_tag "exam[problem_ids][]", prob.id, @exam.problems.include?(prob) %></td>
          <td><%= prob.question %></td>
          <td><%= prob.answer %></td>
          <td><%= link_to "Edit", edit_problem_path(prob) %></td>
        </tr>
      <% end %>
    <% end %>
  </table>

  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/exams/edit.html.erb
<h2>Editing a Quiz</h2>

<%= render 'form' %>

app/views/exams/index.html.erb
<h1>All the Quizzes!</h1>

<% if user_signed_in? && current_user.is_teacher %>
</p>
  <%= link_to "Create a new Quiz", new_exam_path %>
</p>
<% end %>

<table>
  <tr>
    <th></th>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @exams.each_with_index do |exam, index| %>
    <tr>
      <td><%= index+1 %></td>
      <td><% if user_signed_in? && current_user.is_teacher %><%= link_to exam.title, exam_path(exam) %><% else %><strong><%= exam.title %></strong><% end %></td>
      <td><%= pluralize(exam.problems.count, "Question") %></td>
      <td><%= link_to "Take Quiz", take_exam_path(exam) %></td>
      <td><% if user_signed_in? && current_user.is_teacher %><%= link_to "Destroy", exam_path(exam), method: :delete %><% end %></td>
    </tr>
  <% end %>
</table>

app/views/exams/new.html.erb
<h1>Create a New Quiz</h1>
<h3>Enter a Title, then select the questions you want to be on the quiz. Simple!</h3>

<%= render 'form' %>

app/views/exams/result.html.erb
<h1>Here are your results!</h1>
<h2>for taking Quiz "<%= @exam.title %>"</h2>

<h3>You got <%= @exam_reporter.score %> out of <%= @exam_reporter.total_possible %>!</h3>

<table>
  <tr>
    <th>No.</th>
    <th>Question</th>
    <th>Correct Answer</th>
    <th>Your Answer</th>
  </tr>

  <% @exam_reporter.results.each_with_index do |current_result, index| %>
    <% if current_result.score == 0 %><tr class="bold"><% else %><tr><% end %>
      <td><%= index+1 %></td>
      <td><%= current_result.question %></td>
      <td><%= current_result.correct_answer %></td>
      <td><%= current_result.user_answer %></td>
    </tr>
  <% end %>
</table>

<h3><%= link_to 'Retake this Quiz', take_exam_path(@exam) %></h3>

app/views/exams/show.html.erb
<h2><%= @exam.title %></h2>

<h3>Questions in this Quiz:</h3>

<table>
  <tr>
    <th>No.</th>
    <th>Question</th>
    <th>Answer</th>
    <th></th>
  </tr>

  <% @exam.problems.each_with_index do |prob, index| %>
    <tr>
      <td><%= index+1 %>
      <td><%= prob.question %></td>
      <td><%= prob.answer %></td>
      <td><%= link_to "Edit", edit_problem_path(prob) %></td>
    </tr>
  <% end %>
</table>

<h3><%= link_to "Edit this Quiz", edit_exam_path(@exam) %></h3>
<h3><%= link_to "Destroy this Quiz", exam_path(@exam), method: :delete, data: { confirm: "Are you sure?" } %></h3>

app/views/exams/take.html.erb
<h1>We're taking a Quiz!</h1>
<h2><%= @exam.title %></h2>

<%= form_tag(result_exam_path, method: "post") do %>
  <table>
    <tr>
      <th>No.</th>
      <th>Question</th>
      <th></th>
      <th></th>
    </tr>

    <% @exam.problems.each_with_index do |prob, index| %>
      <tr>
        <td><%= index+1 %></td>
        <td><%= label_tag prob.question %></td>
        <td> = </td>
        <td><%= text_field_tag "answers[" + prob.id.to_s + "]" %></td>
      </tr>
    <% end %>
  </table>

  <%= submit_tag("Submit!") %>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<h3>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>
</h3>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>

    <%= render 'common/session' %>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<%= link_to 'Home', root_path, class: 'navbar-brand' %>
<%= link_to 'Quizzes', exams_path, class: 'navbar-brand' %>
<% if user_signed_in? && current_user.is_teacher %><%= link_to 'Problems', problems_path, class: 'navbar-brand' %><% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Quiz" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Quiz" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       
       <%= yield %>
    </main>
  </body>
</html>

app/views/problems/_form.html.erb
<%= form_for @problem do |f| %>
  <% if @problem.errors.any? %>
    <div class="error_explanation">
      <h2><%= pluralize(@problem.errors.count, "error") %> prevented this Math Problem from being saved:</h2>
      <ul>
        <% @problem.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :question %><br />
    <%= f.text_area :question %>
  </p>

  <p>
    <%= f.label :answer %><br />
    <%= f.text_area :answer %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/problems/edit.html.erb
<h1>Edit a Math Problem:</h1>

<%= render 'form' %>

app/views/problems/index.html.erb
<h1>All the Math Problems!</h1>

<p><%= link_to "Create a new Math Problem", new_problem_path %></p>

<table>
  <tr>
    <th></th>
    <th>Question</th>
    <th>Answer</th>
    <th></th>
    <th></th>
  </tr>

  <% @problems.each_with_index do |problem, index| %>
    <tr>
      <td><%= index+1 %></td>
      <td><%= problem.question %></td>
      <td><%= problem.answer %></td>
      <td><%= link_to "Edit", edit_problem_path(problem) %></td>
      <td><%= link_to "Destroy", problem_path(problem), method: :delete %></td>
    </tr>
  <% end %>
</table>

app/views/problems/new.html.erb
<h1>Let's Create a Math Problem!</h1>

<%= render 'form' %>

app/views/problems/show.html.erb
<h2>Question:</h2>
<h3><%= @problem.question %></h3>

<h2>Answer:</h2>
<h3><%= @problem.answer %></h3>

<br />
<h4><%= link_to "Edit this Math Problem", edit_problem_path(@problem) %></h4>
<h4><%= link_to "Create another Math Problem", new_problem_path %></h4>

app/views/welcome/index.html.erb
<h1>Welcome to the Quizinator!</h1>
<h2>"Come with me if you want to math!"</h2>

<% if user_signed_in? && current_user.is_teacher %><h3><%= link_to "All Math Problems", controller: "problems" %></h3><% end %>
<h3><%= link_to "All Quizzes", controller: "exams" %></h3>